- name: Demo on play level Variables
  hosts: all
  vars:
    url: play.example.com
  tasks:
    - name: print url
      ansible.builtin.debug:
        msg: URL - {{url}}

- name: Demo on play level Variables
  hosts: all
  tasks:
    - name: print url
      ansible.builtin.debug:
        msg: URL - {{url}}
      vars:
        url: tasks.example.com
#only task can access variable in above code


#load vars from file
- name: load vars from file
  hosts: all
  vars_files:
    - exvars.yml
  tasks:
    - name: print url
      ansible.builtin.debug:
        msg: URL - {{url}}

#load variables from roles:
- name: variable from role1
  hosts: all
  roles:
    - sample
    - sample2

#shell command from ansible
- name : Demo on register variable
  hosts: all
  tasks:
    - name: run uptime shell command
      ansible.builtin.shell: uptime
      register: output
    - name: printing output
      ansible.builtin.debug:
        msg: "{{ output }}"
